lib/its_web/router.ex
defmodule ItsWeb.Router do
  use ItsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-in", SessionController, :delete
    post "/sign-up", SessionController, :sign_up
  end

  scope "/admin", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AdminController, :index_all
    get "/clients", AdminController, :index_clients
    get "/techs", AdminController, :index_tech
    post "/", AdminController, :create
    delete "/:id/:tab", AdminController, :delete
    put "/:id", AdminController, :update
    get "/tickets", AdminController, :tickets
    delete "/tickets/:id/delete", AdminController, :ticket_delete
    get "/ticket/:ticketid", AdminController, :show_ticket
    delete "/ticket/:ticketid/task/:taskid", AdminController, :delete_task
    post "/search", AdminController, :search
  end

  scope "/admin/tickets", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/pending", AdminController, :tickets_pending
    get "/tasks", AdminController, :tasks
    get "/assigned", AdminController, :to_others
    get "/:id", AdminController, :show
    put "/:id/tech", AdminController, :assign
    post "/:id/task", AdminController, :create_task
    put "/:ticketid/task/:taskid", AdminController, :update_task
    put "/:id", AdminController, :update_ticket
    post "/search", AdminController, :search_ticket
    get "/print/:id", AdminController, :print_ticket
  end

  scope "/admin/profile", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AdminController, :profile_setting
    put "/:id", AdminController, :update_profile
  end

  scope "/admin/devices", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AdminController, :devices
    post "/", AdminController, :create_device
    put "/:id", AdminController, :update_device
    delete "/delete/:id", AdminController, :delete_device
    post "/search", AdminController, :search_device
  end

  scope "/client", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", ClientController, :index
    post "/", ClientController, :create
    get "/active", ClientController, :active
    get "/pending", ClientController, :pending
    get "/discarded", ClientController, :discarded
    get "/done", ClientController, :done
    put "/:id", ClientController, :update
    put "ticket/:id", ClientController, :update_ticket_status
    delete "/:id", ClientController, :delete
    get "/show/:id", ClientController, :show
    get "/ticket/:id/print", ClientController, :print
    post "/ticket/:id/search", ClientController, :search_ticket
  end

  scope "/client/profile", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", ClientController, :profile_setting
    put "/:id", ClientController, :update_profile
  end

  scope "/headtech", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HeadtechController, :index
    get "/tasks", HeadtechController, :tasks
    get "/assigned", HeadtechController, :to_others
    put "/ticket/:id/tech", HeadtechController, :assign
    get "/ticket/:id", HeadtechController, :show
    put "/ticket/:id", HeadtechController, :update
    post "/ticket/:id/task", HeadtechController, :create_task
    put "/ticket/:ticketid/task/:taskid", HeadtechController, :update_task
    delete "/ticket/:ticketid/task/:taskid", HeadtechController, :delete_task
  end

  scope "/headtech/profile", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", HeadtechController, :profile_setting
    put "/:id", HeadtechController, :update_profile
  end

  scope "/tech", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", TechController, :index
    get "/done", TechController, :done
    get "/ticket/:id", TechController, :show
    put "/ticket/:id", TechController, :update
    post "/ticket/:id/search", TechController, :search_ticket
    get "/ticket/:id/print", TechController, :print
    post "/ticket/:id", TechController, :create_task
    put "/ticket/:ticketid/task/:taskid", TechController, :update_task
    delete "/ticket/:ticketid/task/:taskid", TechController, :delete_task
  end

  scope "/tech/profile", ItsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", TechController, :profile_setting
    put "/:id", TechController, :update_profile
  end

  # Other scopes may use custom stacks.
  # scope "/api", ItsWeb do
  #   pipe_through :api
  # end
end

lib/its_web/views/layout_view.ex
defmodule ItsWeb.LayoutView do
  use ItsWeb, :view
end

lib/its_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ITS</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top navbar-5-pad">
      <a class="navbar-brand" href="/">
        <img src=<%= static_path(@conn, "/images/ios-banner2.png")%> height="40px">
        ITSeastwestBPO |
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <%= if signed_in?(@conn) do %>
          <%= case check_user_type(@conn) do %>
            <% "admin" -> %>
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-users"></i> Accounts
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link [to: admin_path(@conn, :index_all), class: "dropdown-item"] do %>
                  All Users
                <% end %>
              </div>
            </li>

            <li class="nav-item">
              <%= link [to: admin_path(@conn, :devices), class: "nav-link"] do %>
                <i class="fas fa-laptop"></i>&nbsp;Devices
              <% end %>
            </li>

            <li class="nav-item">
              <%= link [to: admin_path(@conn, :tickets), class: "nav-link"] do %>
                <i class="fas fa-ticket-alt"></i>&nbsp;Tickets
                  &nbsp;<span class="badge badge-pill badge-warning <%= if Its.Issue.count_pending_tickets() == 0, do: "hide" %>" style="float:right;margin-bottom:-10px;">
                    <%= Its.Issue.count_pending_tickets() %>
                  </span>
              <% end %>
            </li>

            <% "client" -> %>
              <li class="nav-item">
                <%= link [to: client_path(@conn, :index), class: "nav-link"] do %>
                  <i class="fas fa-ticket-alt"></i>&nbsp;Tickets
                <% end %>
              </li>

            <% "technician" -> %>
              <li class="nav-item">
                <%= link [to: tech_path(@conn, :index), class: "nav-link"] do %>
                  <i class="fas fa-ticket-alt"></i>&nbsp;Tickets
                <% end %>
              </li>

            <% "headtech" -> %>
              <li class="nav-item">
                <%= link [to: headtech_path(@conn, :index), class: "nav-link"] do %>
                  <i class="fas fa-ticket-alt"></i>&nbsp;Tickets
                  &nbsp;<span class="badge badge-pill badge-warning <%= if Its.Issue.count_pending_tickets() == 0, do: "hide" %>" style="float:right;margin-bottom:-10px;">
                    <%= Its.Issue.count_pending_tickets() %>
                  </span>
                <% end %>
              </li>

            <% _ -> %>

          <% end %>
        <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
            <%= if signed_in?(@conn) do %>
              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-cog"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link [
                            to:
                            case check_user_type(@conn) do
                              "admin" ->
                                admin_path(@conn, :profile_setting)

                              "client" ->
                                client_path(@conn, :profile_setting)

                              "headtech" ->
                                headtech_path(@conn, :profile_setting)

                              "technician" ->
                                tech_path(@conn, :profile_setting)

                              _ ->
                                "#"
                            end,
                              class: "dropdown-item"] do %>
                    <i class="fas fa-users-cog"></i>&nbsp; Profile Setting
                  <% end %>
                  <div class="dropdown-divider"></div>
                  <div class="dropdown-item">
                    <i class="fas fa-question"></i>&nbsp; Help
                  </div>
                </div>
              </li>
            <%end%>

            <form class="form-inline my-2 my-lg-0">
              <%= if signed_in?(@conn) do %>
                <%= link [to: session_path(@conn, :delete), class: "nav-link link-white active", method: "delete"] do %>
                  <%= case check_user_type(@conn) do %>
                    <% "admin" -> %>
                      <i class="fas fa-user-astronaut"></i>

                    <% "technician" -> %>
                      <i class="fas fa-user-tie"></i>

                    <% "client" -> %>
                      <i class="fas fa-user"></i>

                    <% "headtech" -> %>
                      <i class="fas fa-user-secret"></i>

                    <% _ -> %>

                  <% end %>
                  <i class="fas fa-sign-out-alt"></i>&nbsp;Sign Out
                <% end %>
              <% else %>
                <%= link to: session_path(@conn, :new), class: "nav-link link-white active" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  &nbsp;
                  <%= unless @admin_count == 0 do  %>
                    Sign In
                  <% else %>
                    Sign Up
                  <% end %>
                  &nbsp;&nbsp;&nbsp;
                <% end %>
              <% end %>
            </form>
        </ul>

      </div>
    </nav>

      <main role="main">
        <div class="container-fluid">
          <div class="row fixed-bottom">
            <div class="col-sm-10 fixed-bottom"></div>
            <div class="col-sm-1 ml-auto fixed-bottom">
              <div class="row ml-auto">

              <div class="col-sm-4 <%= unless signed_in?(@conn), do: 'hide' %>">
                <div class="btn-group dropleft">
                  <button type="button" class="round btn btn-outline-warning" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-tie"></i>
                  </button>
                  <div class="dropdown-menu">
                    <h6 class="dropdown-header">Online Technicians</h6>
                    <% online_techs = Its.Accounts.list_online_users(["technician", "headtech", "admin"])%>
                    <%= for tech <- online_techs do %>
                    <a class="dropdown-item" href="#">
                      <i class="fas fa-user-circle text-warning"></i> &nbsp; <%= tech.first_name <> " " <> tech.last_name %>
                    </a>
                   <% end %>
                  </div>
                </div>
              </div>

              </div>
            </div>
          </div>

          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>